# Generated by Django 4.1.7 on 2023-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('r1', models.FloatField()),
                ('r2', models.FloatField()),
                ('r3', models.FloatField()),
                ('m1', models.FloatField()),
                ('m2', models.FloatField()),
                ('m3', models.FloatField()),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('d1', models.FloatField()),
            ],
        ),
    ]
