# Generated by Django 4.1.7 on 2023-02-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GasPrices',
        ),
    ]
